/**
 * PESAKI Forex — HTTP API.
 *
 * Registered under /forex, deliberately separate from the binary prediction
 * game at /games/fx. This module owns its own accounts, orders, positions,
 * fills and ledger, and its own market-data engine.
 *
 * Identity always comes from the verified Supabase session (verifyAuth). The
 * user_id in a request body is never trusted; every query is scoped to the
 * authenticated user and their own account.
 *
 * Prices come from PESAKI's own internal market engine (see
 * services/forex/marketEngine). They are generated by this process, not taken
 * from an interbank feed, and the API labels them `pesaki-engine` so a client
 * cannot mistake them for a real market price.
 */

import { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { z } from "zod";
import { verifyAuth } from "../../middleware/auth";
import { supabase } from "../../lib/supabase";
import { logger } from "../../utils/logger";
import { INSTRUMENTS, SYMBOLS, getInstrument, type InstrumentSpec } from "../../services/forex/instruments";
import {
  INTERVALS,
  getEngine,
  type Candle,
  type Interval,
  type Quote,
} from "../../services/forex/marketEngine";
import { kesPerUnit } from "../../services/forex/kesRates";
import {
  calculatePositionSize,
  computePnl,
  configuredLeverage,
  marginForLots,
  marginState,
  minTradeAmount,
  sizeFromTradeAmount,
  validateLots,
  validateStopLoss,
  validateTakeProfit,
  validateTradeAmount,
} from "../../services/forex/risk";

const DEMO_START_BALANCE = 100_000;

/**
 * Server-side switch for real-money trading.
 *
 * When false, a REAL account cannot be funded or traded, so no user funds can
 * reach this module. This is deliberately read only from the environment: a
 * `?mode=real` query parameter must never be enough to enable real trading.
 */
const REAL_TRADING_ENABLED = process.env.PESAKI_FX_REAL_ENABLED === "true";

/** Structured error codes. Predictable validation failures never surface as 500. */
export const FX_ERRORS = {
  INVALID_ORDER: 400,
  UNAUTHORIZED: 401,
  ACCOUNT_DISABLED: 403,
  MARKET_UNAVAILABLE: 409,
  INVALID_POSITION_SIZE: 422,
  INVALID_PRICE: 422,
  INSUFFICIENT_BALANCE: 403,
  INSUFFICIENT_MARGIN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL: 500,
} as const;

export type FxErrorCode = keyof typeof FX_ERRORS;

class ForexError extends Error {
  constructor(
    readonly code: FxErrorCode,
    message: string,
    readonly detail?: Record<string, unknown>,
  ) {
    super(message);
    this.name = "ForexError";
  }
}

/** KES value of one unit of the instrument's quote currency. */
const quoteToKes = (instrument: InstrumentSpec): number => kesPerUnit(instrument.quote);

/** Resolve the canonical symbol for a DB instrument id. */
const symbolCache = new Map<number, string>();

async function symbolForInstrument(instrumentId: number): Promise<string | undefined> {
  if (instrumentId <= 0) return undefined;
  const cached = symbolCache.get(instrumentId);
  if (cached) return cached;
  const { data } = await supabase
    .from("forex_instruments")
    .select("symbol")
    .eq("id", instrumentId)
    .maybeSingle();
  if (data?.symbol) {
    symbolCache.set(instrumentId, data.symbol);
    return data.symbol;
  }
  return undefined;
}

async function getOrCreateAccount(userId: string, accountType: "demo" | "live") {
  const { data, error } = await supabase
    .from("forex_accounts")
    .select("*")
    .eq("user_id", userId)
    .eq("account_type", accountType)
    .maybeSingle();
  if (error) throw error;
  if (data) return data;

  // REAL is gated on a server-side switch. A `?mode=real` query parameter or a
  // request body flag is never sufficient on its own: the caller must already
  // hold an authenticated session, and this process must have real trading
  // switched on. When the switch is off, REAL is refused with a structured
  // error rather than a UI modal that pretends the mode does not exist.
  if (accountType === "live" && !REAL_TRADING_ENABLED) {
    throw new ForexError(
      "ACCOUNT_DISABLED",
      "Real-money forex trading is not enabled on this deployment.",
      { mode: "live" },
    );
  }

  const { data: created, error: insertError } = await supabase
    .from("forex_accounts")
    .insert({
      user_id: userId,
      account_type: accountType,
      currency: "KES",
      // A real account starts at zero: the wallet is the source of truth for
      // real funds. Seeding it with a demo-style balance would fabricate money.
      balance: accountType === "demo" ? DEMO_START_BALANCE : 0,
      equity: accountType === "demo" ? DEMO_START_BALANCE : 0,
      // Leverage is a plain multiplier and must match what the order path sizes
      // against, otherwise the server-side margin check would reserve a
      // different amount of margin than the ticket promised the user.
      leverage: configuredLeverage(),
      status: "active",
    })
    .select()
    .single();
  if (insertError) throw insertError;
  return created;
}

const orderSchema = z.object({
  symbol: z.enum(SYMBOLS as [string, ...string[]]),
  side: z.enum(["buy", "sell"]),
  // Trade amount is the committed KES capital and the only user-supplied size
  // input. Lots are derived server-side from it and the configured leverage, so
  // the client can never size its own position or state its own leverage.
  trade_amount: z.number().positive().optional(),
  // Retained so existing clients and the risk calculator keep working. When
  // trade_amount is absent the request is treated as a lot-sized order.
  lots: z.number().positive().optional(),
    order_type: z.enum(["market", "limit", "stop", "stop_limit"]).default("market"),
  limit_price: z.number().positive().nullable().optional(),
  trigger_price: z.number().positive().nullable().optional(),
  stop_loss: z.number().positive().nullable().optional(),
  take_profit: z.number().positive().nullable().optional(),
  account_type: z.enum(["demo", "live"]).default("demo"),
  idempotency_key: z.string().min(8).max(120).optional(),
});

const bad = (reply: FastifyReply, error: string, code = 400) =>
  reply.code(code === 403 ? 403 : 400).send({ success: false, error, code: "REJECTED" });

export const forexRoutes = async (fastify: FastifyInstance) => {
  // ─── Instruments ───────────────────────────────────────────────────────────
  fastify.get("/instruments", async () => {
    const { data } = await supabase
      .from("forex_instruments")
      .select("*")
      .order("symbol");
    const rows =
      data?.length
        ? data
        : Object.values(INSTRUMENTS).map((s) => ({
            id: 0,
            symbol: s.symbol,
            base_currency: s.base,
            quote_currency: s.quote,
            digits: s.digits,
            pip_size: s.pipSize,
            min_lot: s.minLot,
            max_lot: s.maxLot,
            lot_step: s.lotStep,
            typical_spread_pips: s.typicalSpreadPips,
            trading_status: "open",
          }));
    return { success: true, instruments: rows };
  });

  // ─── Market ─────────────────────────────────────────────────────────────────
  // Engine status for the client. This is what lets the UI say MARKET OPEN /
  // MARKET PAUSED instead of the misleading "LIVE" it used to show while the
  // account was on demo.
  fastify.get("/market", async () => {
    const engine = getEngine();
    return { success: true, market: engine.describe() };
  });

  // ─── Quotes ────────────────────────────────────────────────────────────────
  fastify.get("/quotes", async (request, reply) => {
    const { symbols } = request.query as { symbols?: string };
    const list = (symbols ? symbols.split(",") : SYMBOLS).map((s) => s.toUpperCase());
    const engine = getEngine();
    const quotes: Quote[] = engine.quoteAll(list);
    if (quotes.length === 0) {
      return reply.code(FX_ERRORS.MARKET_UNAVAILABLE).send({
        success: false,
        error: "No supported pairs were requested.",
        code: "MARKET_UNAVAILABLE",
      });
    }
    return {
      success: true,
      quotes,
      // Daily change and session extremes drive the market-watch list.
      watch: Object.fromEntries(quotes.map((q) => [q.symbol, engine.dailyChange(q.symbol)])),
      state: engine.state,
    };
  });

  fastify.get("/quote/:symbol", async (request, reply) => {
    const { symbol } = request.params as { symbol: string };
    if (!getInstrument(symbol.toUpperCase())) {
      return bad(reply, "Unsupported symbol");
    }
    try {
      return { success: true, quote: getEngine().quote(symbol.toUpperCase()) };
    } catch (err) {
      logger.error({ err: (err as Error).message }, "Forex quote failed");
      return reply.code(FX_ERRORS.MARKET_UNAVAILABLE).send({
        success: false,
        error: "Market price is currently unavailable.",
        code: "MARKET_UNAVAILABLE",
      });
    }
  });

  // ─── Candles ───────────────────────────────────────────────────────────────
  // The symbol arrives as a query parameter, not a path segment. A symbol
  // contains a slash ("EUR/USD"), so a path form like /candles/EUR/USD never
  // matched the single-segment route and always returned 404.
  fastify.get("/candles", async (request, reply) => {
    const { symbol, interval, count } = request.query as {
      symbol?: string;
      interval?: string;
      count?: string;
    };
    const sym = (symbol ?? "").toUpperCase();
    if (!sym || !getInstrument(sym)) {
      return bad(reply, "A valid symbol is required, e.g. ?symbol=EUR%2FUSD");
    }
    const iv = ((interval ?? "5m") as Interval) in INTERVALS ? ((interval ?? "5m") as Interval) : "5m";
    const n = Math.min(Math.max(Number(count) || 120, 1), 1000);

    try {
      const candles: Candle[] = getEngine().getCandles(sym, iv, n);
      return {
        success: true,
        symbol: sym,
        interval: iv,
        provider: "pesaki-engine",
        candles: candles.map((c) => ({
          time: c.timestamp,
          timestamp: c.timestamp,
          open: c.open,
          high: c.high,
          low: c.low,
          close: c.close,
          tickVolume: c.tickVolume,
        })),
      };
    } catch (err) {
      logger.error({ err: (err as Error).message, symbol: sym }, "Forex candles failed");
      return reply.code(FX_ERRORS.MARKET_UNAVAILABLE).send({
        success: false,
        error: "Chart data is currently unavailable.",
        code: "MARKET_UNAVAILABLE",
      });
    }
  });

  // Legacy path form retained only so an older client gets a clear explanation
  // instead of an opaque 404.
  fastify.get("/candles/*", async (_request, reply) =>
    reply.code(FX_ERRORS.INVALID_ORDER).send({
      success: false,
      error: "Use /forex/candles?symbol=EUR%2FUSD&interval=5m&count=120",
      code: "INVALID_ORDER",
    }),
  );

  // ─── Account ───────────────────────────────────────────────────────────────
  fastify.get("/account", { preHandler: [verifyAuth] }, async (request, reply) => {
    const accountType = ((request.query as { account_type?: string }).account_type ??
      "demo") as "demo" | "live";
    try {
      const account = await getOrCreateAccount(request.user!.id, accountType);
      const { data: positions } = await supabase
        .from("forex_positions")
        .select("*")
        .eq("account_id", account.id)
        .is("closed_at", null);

      let unrealised = 0;
      let usedMargin = Number(account.used_margin ?? 0);
      const enriched = [];
      // Positions we managed to price, so the mark-to-market can be persisted.
      const marked: { id: string; price: number; q2k: number }[] = [];
      for (const p of positions ?? []) {
        const sym = await symbolForInstrument(p.instrument_id);
        const spec = sym ? getInstrument(sym) : undefined;
        if (!spec) {
          enriched.push(p);
          continue;
        }
        try {
          const quote = getEngine().quote(spec.symbol);
          const mid = quote.mid;
          const q2k = quoteToKes(spec);
          const pnl = computePnl({
            side: p.side,
            lots: Number(p.quantity),
            entryPrice: Number(p.average_entry_price),
            exitPrice: mid,
            instrument: spec,
            quoteToKes: q2k,
          });
          unrealised += pnl;
          // Accumulate across every open position. Assigning here reported only
          // the margin of whichever position happened to be last in the list.
          usedMargin += Number(p.margin ?? 0);
          marked.push({ id: p.id, price: mid, q2k });
          enriched.push({ ...p, current_price: mid, unrealised_pnl: pnl });
        } catch {
          enriched.push({ ...p, unrealised_pnl: 0, priceStatus: "unavailable" });
        }
      }

      // Persist the marks so database-side equity reflects live prices. Without
      // this the stored current_price stays at entry forever and equity never
      // moves between opens and closes.
      if (marked.length > 0) {
        await Promise.all(
          marked.map((m) =>
            supabase
              .from("forex_positions")
              .update({ current_price: m.price, quote_to_kes: m.q2k })
              .eq("id", m.id)
              .eq("user_id", request.user!.id),
          ),
        );
        const { error: equityError } = await supabase.rpc("forex_recalculate_equity", {
          p_account_id: account.id,
        });
        if (equityError) {
          logger.warn({ err: equityError.message }, "Forex equity refresh failed");
        }
      }

      const state = marginState(Number(account.balance), unrealised, usedMargin);
      const { data: ledger } = await supabase
        .from("forex_transactions")
        .select("*")
        .eq("account_id", account.id)
        .order("created_at", { ascending: false })
        .limit(5);

      return {
        success: true,
        account: {
          // Normalised to camelCase to match the computed state, and carrying
          // the leverage the server actually sized the position with. `state`
          // supplies the authoritative balance/equity/margin figures.
          id: account.id,
          account_type: account.account_type,
          leverage: Number(account.leverage ?? 1),
          status: account.status,
          ...state,
        },
        positions: enriched,
        recentTransactions: ledger ?? [],
        realTradingEnabled: REAL_TRADING_ENABLED,
      };
    } catch (err) {
      // A ForexError carries a deliberate status (403 for a gated live account).
      // Anything else is a genuine fault: log it in full and report it honestly
      // rather than flattening every failure to an opaque 500.
      const status = (err as { statusCode?: number }).statusCode ?? 500;
      if (status === 500) {
        logger.error({ err }, "Forex account load failed");
        return reply.code(500).send({
          success: false,
          error: "Could not load your Forex account.",
          code: "ACCOUNT_LOAD_FAILED",
        });
      }
      return reply.code(status).send({
        success: false,
        error: status === 403 ? "Live trading is currently unavailable." : (err as Error).message,
      });
    }
  });

  // ─── Risk calculator ───────────────────────────────────────────────────────
  fastify.post("/risk/preview", async (request, reply) => {
    const schema = z.object({
      symbol: z.enum(SYMBOLS as [string, ...string[]]),
      side: z.enum(["buy", "sell"]),
      balance: z.number().positive(),
      risk_percent: z.number().positive().max(100),
      entry_price: z.number().positive(),
      stop_loss: z.number().positive(),
    });
    const parsed = schema.safeParse(request.body);
    if (!parsed.success) return bad(reply, "Invalid risk inputs");
    const { symbol, side, balance, risk_percent, entry_price, stop_loss } = parsed.data;
    const spec = getInstrument(symbol)!;

    const slCheck = validateStopLoss(side, entry_price, stop_loss);
    if (!slCheck.ok) return bad(reply, slCheck.error!);

    try {
      const q2k = quoteToKes(spec);
      const preview = calculatePositionSize({
        balance,
        riskPercent: risk_percent,
        entryPrice: entry_price,
        stopLossPrice: stop_loss,
        instrument: spec,
        quoteToKes: q2k,
      });
      const quote = getEngine().quote(symbol);
      const riskDistance = Math.abs(entry_price - stop_loss);
      const rewardDistance = riskDistance * 2;
      return {
        success: true,
        preview: {
          ...preview,
          entrySpreadPips: quote.spreadPips,
          riskRewardRatio: riskDistance > 0 ? Number((rewardDistance / riskDistance).toFixed(2)) : 0,
          potentialLoss: Number((preview.lots * spec.contractSize * riskDistance * q2k).toFixed(2)),
          potentialProfit: Number(
            (preview.lots * spec.contractSize * rewardDistance * q2k).toFixed(2),
          ),
        },
      };
    } catch {
      return reply.code(503).send({ success: false, error: "Market data is currently unavailable." });
    }
  });

  // ─── Place order ───────────────────────────────────────────────────────────
  fastify.post("/orders", { preHandler: [verifyAuth] }, async (request, reply) => {
    const parsed = orderSchema.safeParse(request.body);
    if (!parsed.success) return bad(reply, "Invalid order details");
    const body = parsed.data;
    const userId = request.user!.id;
    const spec = getInstrument(body.symbol);
    if (!spec) return bad(reply, "This instrument is not available");

    if (body.account_type === "live" && !REAL_TRADING_ENABLED) {
      return bad(reply, "Live trading is currently unavailable. Use Demo trading.", 403);
    }

    // Idempotency: a repeated submit must not create a second order.
    if (body.idempotency_key) {
      const { data: existing } = await supabase
        .from("forex_orders")
        .select("*")
        .eq("user_id", userId)
        .eq("idempotency_key", body.idempotency_key)
        .maybeSingle();
      if (existing) return { success: true, order: existing, idempotent: true };
    }

    let account;
    try {
      account = await getOrCreateAccount(userId, body.account_type);
    } catch (err) {
      const status = (err as { statusCode?: number }).statusCode ?? 500;
      return reply
        .code(status)
        .send({ success: false, error: "Live trading is currently unavailable.", code: "REJECTED" });
    }
    if (account.status !== "active") return bad(reply, "Your Forex account is not active");

    const { data: instrumentRow } = await supabase
      .from("forex_instruments")
      .select("*")
      .eq("symbol", body.symbol)
      .maybeSingle();
    if (!instrumentRow) return bad(reply, "This instrument is not available");
    if (instrumentRow.trading_status !== "open") return bad(reply, "This instrument is closed");

    let quote: Quote;
    try {
      quote = getEngine().quote(body.symbol);
    } catch {
      return reply.code(503).send({
        success: false,
        error: "Market data is currently unavailable. No order was placed.",
        code: "MARKET_DATA_UNAVAILABLE",
      });
    }

    const entry =
      body.order_type === "market"
        ? body.side === "buy"
          ? quote.ask
          : quote.bid
        : (body.limit_price ?? body.trigger_price ?? quote.mid);

    const slCheck = validateStopLoss(body.side, entry, body.stop_loss ?? null);
    if (!slCheck.ok) return bad(reply, slCheck.error!);
    const tpCheck = validateTakeProfit(body.side, entry, body.take_profit ?? null);
    if (!tpCheck.ok) return bad(reply, tpCheck.error!);

    const q2k = quoteToKes(spec);
    const leverage = configuredLeverage();
    const isPending = ["limit", "stop", "stop_limit"].includes(body.order_type);

    // Size the position. When the client commits a KES trade amount the server
    // derives the lots; otherwise a lot-sized request is validated as such.
    const sizing = (() => {
      if (body.trade_amount != null) {
        return sizeFromTradeAmount({
          tradeAmount: body.trade_amount,
          entryPrice: entry,
          instrument: spec,
          quoteToKes: q2k,
          leverage,
        });
      }
      const lots = body.lots!;
      return {
        tradeAmount: 0,
        exposure: lots * spec.contractSize * entry * q2k,
        units: lots * spec.contractSize,
        margin: marginForLots(lots, entry, spec, q2k, 100 / leverage),
        lots,
        notionalPerLot: spec.contractSize * entry * q2k,
      };
    })();

    const freeMargin = Number(account.equity ?? account.balance ?? 0) - Number(account.used_margin ?? 0);

    if (body.trade_amount != null) {
      const amountCheck = validateTradeAmount(body.trade_amount, freeMargin);
      if (!amountCheck.ok) return bad(reply, amountCheck.error!);
    } else {
      const lotsCheck = validateLots(body.lots!, spec);
      if (!lotsCheck.ok) return bad(reply, lotsCheck.error!);
      if (sizing.margin > freeMargin) {
        return bad(
          reply,
          `Order rejected: insufficient free margin. You need KSh ${sizing.margin.toFixed(2)}.`,
        );
      }
    }

    // Exposure caps bound the platform's net risk. Because PESAKI runs its own
    // market engine it carries the risk that customers net out against it, so
    // the order is measured against caps before it is allowed to consume margin.
    if (isPending) {
      // A pending order reserves no margin, so it is not exposure yet.
    } else {
      const { data: config } = await supabase
        .from("forex_market_config")
        .select("max_exposure_per_account, max_exposure_per_symbol, max_total_exposure")
        .eq("id", 1)
        .maybeSingle();

      const { data: openPositions } = await supabase
        .from("forex_positions")
        .select("instrument_id, quantity, average_entry_price, quote_to_kes")
        .eq("account_id", account.id)
        .eq("status", "open");

      let accountExposure = 0;
      let symbolExposure = 0;
      for (const p of openPositions ?? []) {
        const notional =
          Number(p.quantity) *
          spec.contractSize *
          Number(p.average_entry_price) *
          Number(p.quote_to_kes ?? q2k);
        accountExposure += notional;
        if (p.instrument_id === instrumentRow.id) symbolExposure += notional;
      }

      const proposed = accountExposure + sizing.exposure;
      const perAccount = Number(config?.max_exposure_per_account ?? 0);
      const perSymbol = Number(config?.max_exposure_per_symbol ?? 0);
      const total = Number(config?.max_total_exposure ?? 0);

      if (perAccount > 0 && proposed > perAccount) {
        return bad(
          reply,
          `Order rejected: this would raise your exposure to KSh ${proposed.toFixed(2)}, above the per-account limit of KSh ${perAccount.toFixed(2)}.`,
        );
      }
      if (perSymbol > 0 && symbolExposure + sizing.exposure > perSymbol) {
        return bad(
          reply,
          `Order rejected: this would exceed the exposure limit for ${spec.symbol}.`,
        );
      }
      if (total > 0) {
        const { data: allOpen } = await supabase
          .from("forex_positions")
          .select("quantity, average_entry_price, quote_to_kes")
          .eq("status", "open");
        let platformExposure = 0;
        for (const p of allOpen ?? []) {
          platformExposure +=
            Number(p.quantity) *
            spec.contractSize *
            Number(p.average_entry_price) *
            Number(p.quote_to_kes ?? q2k);
        }
        if (platformExposure + sizing.exposure > total) {
          return bad(reply, "Order rejected: platform exposure limit reached. Please try again later.");
        }
      }
    }

    const executedPrice = body.side === "buy" ? quote.ask : quote.bid;
    const slippage = Number((executedPrice - quote.mid).toFixed(spec.digits));

    // Execution runs entirely inside one database transaction: the order, the
    // position, the fill and the margin reservation either all land or none do.
    // Margin is re-checked under a row lock on the account, so two concurrent
    // orders cannot both spend the same free margin.
    const { data: result, error: execError } = await supabase.rpc("forex_open_market_position", {
      p_user_id: userId,
      p_account_id: account.id,
      p_instrument_id: instrumentRow.id,
      p_order_type: body.order_type,
      p_side: body.side,
      p_quantity: sizing.lots,
      p_requested_price: quote.mid,
      p_executed_price: executedPrice,
      p_slippage: slippage,
      p_quote_to_kes: q2k,
      p_limit_price: body.limit_price ?? null,
      p_trigger_price: body.trigger_price ?? null,
      p_stop_loss: body.stop_loss ?? null,
      p_take_profit: body.take_profit ?? null,
      p_idempotency_key: body.idempotency_key ?? null,
      p_pending: isPending,
    });

    if (execError) {
      const reason = execError.message ?? "";
      if (reason.includes("INSUFFICIENT_MARGIN")) {
        const needed = Number(reason.split(":")[1] ?? 0);
        return bad(reply, `Order rejected: insufficient free margin. You need KSh ${needed.toFixed(2)}.`);
      }
      if (reason.includes("ACCOUNT_NOT_ACTIVE")) return bad(reply, "Your Forex account is not active");
      if (reason.includes("INSTRUMENT_CLOSED")) return bad(reply, "This instrument is closed");
      logger.error({ err: reason }, "Forex execution failed");
      return reply.code(500).send({
        success: false,
        error: "The order could not be executed. Nothing was charged or opened.",
        code: "EXECUTION_FAILED",
      });
    }

    if (result?.idempotent) {
      const { data: existing } = await supabase
        .from("forex_orders")
        .select("*")
        .eq("id", result.order_id)
        .maybeSingle();
      return { success: true, order: existing, idempotent: true };
    }

    const [{ data: orderRow }, { data: positionRow }] = await Promise.all([
      supabase.from("forex_orders").select("*").eq("id", result.order_id).maybeSingle(),
      result.position_id
        ? supabase.from("forex_positions").select("*").eq("id", result.position_id).maybeSingle()
        : Promise.resolve({ data: null }),
    ]);

    if (isPending) {
      return { success: true, order: orderRow, message: "Pending order placed" };
    }

    return {
      success: true,
      order: orderRow,
      position: positionRow,
      execution: { requestedPrice: quote.mid, executedPrice, slippage, spreadPips: quote.spreadPips },
      accountType: body.account_type,
    };
  });

  // ─── Orders / positions / history ──────────────────────────────────────────
  fastify.get("/orders", { preHandler: [verifyAuth] }, async (request) => {
    const { data } = await supabase
      .from("forex_orders")
      .select("*")
      .eq("user_id", request.user!.id)
      .order("created_at", { ascending: false })
      .limit(100);
    return { success: true, orders: data ?? [] };
  });

  fastify.get("/positions", { preHandler: [verifyAuth] }, async (request) => {
    const { data } = await supabase
      .from("forex_positions")
      .select("*")
      .eq("user_id", request.user!.id)
      .is("closed_at", null)
      .order("opened_at", { ascending: false });
    return { success: true, positions: data ?? [] };
  });

  fastify.post("/orders/:id/cancel", { preHandler: [verifyAuth] }, async (request, reply) => {
    const { id } = request.params as { id: string };
    const { data: order, error: cancelError } = await supabase
      .from("forex_orders")
      .update({ status: "cancelled", updated_at: new Date().toISOString() })
      .eq("id", id)
      .eq("user_id", request.user!.id)
      .in("status", ["pending", "submitted"])
      .select()
      .maybeSingle();
    if (cancelError) {
      logger.error({ err: cancelError.message }, "Forex order cancel failed");
      return reply.code(500).send({
        success: false,
        error: "The order could not be cancelled. It may still be pending.",
        code: "CANCEL_FAILED",
      });
    }
    if (!order) return reply.code(404).send({ success: false, error: "Order not found or already processed" });
    return { success: true, order };
  });

  fastify.post("/positions/:id/close", { preHandler: [verifyAuth] }, async (request, reply) => {
    const { id } = request.params as { id: string };
    return closePosition(request, reply, id, 1);
  });

  fastify.post("/positions/:id/partial-close", { preHandler: [verifyAuth] }, async (request, reply) => {
    const { id } = request.params as { id: string };
    const schema = z.object({ lots: z.number().positive() });
    const parsed = schema.safeParse(request.body);
    if (!parsed.success) return bad(reply, "Enter a valid partial close size");
    return closePosition(request, reply, id, parsed.data.lots);
  });

  fastify.get("/transactions", { preHandler: [verifyAuth] }, async (request) => {
    const { data } = await supabase
      .from("forex_transactions")
      .select("*")
      .eq("user_id", request.user!.id)
      .order("created_at", { ascending: false })
      .limit(100);
    return { success: true, transactions: data ?? [] };
  });

  fastify.get("/analytics", { preHandler: [verifyAuth] }, async (request) => {
    const { data: closed } = await supabase
      .from("forex_positions")
      .select("*")
      .eq("user_id", request.user!.id)
      .not("closed_at", "is", null);

    const trades = closed ?? [];
    const wins = trades.filter((t) => Number(t.realized_pnl) > 0);
    const losses = trades.filter((t) => Number(t.realized_pnl) < 0);
    const grossProfit = wins.reduce((s, t) => s + Number(t.realized_pnl), 0);
    const grossLoss = Math.abs(losses.reduce((s, t) => s + Number(t.realized_pnl), 0));

    return {
      success: true,
      analytics: {
        totalTrades: trades.length,
        wins: wins.length,
        losses: losses.length,
        winRate: trades.length ? Number(((wins.length / trades.length) * 100).toFixed(1)) : 0,
        grossProfit: Number(grossProfit.toFixed(2)),
        grossLoss: Number(grossLoss.toFixed(2)),
        netPnl: Number((grossProfit - grossLoss).toFixed(2)),
        profitFactor: grossLoss > 0 ? Number((grossProfit / grossLoss).toFixed(2)) : null,
        averageWin: wins.length ? Number((grossProfit / wins.length).toFixed(2)) : 0,
        averageLoss: losses.length ? Number((grossLoss / losses.length).toFixed(2)) : 0,
      },
    };
  });

  /**
   * Reset the demo account.
   *
   * Demo-only and hard-scoped to the authenticated user's demo account, so it
   * can never reach a real account or the wallet regardless of what the client
   * sends. Real funds are not involved in any code path here.
   */
  fastify.post("/account/reset-demo", { preHandler: [verifyAuth] }, async (request, reply) => {
    const userId = request.user!.id;

    const { data: account, error } = await supabase
      .from("forex_accounts")
      .select("id")
      .eq("user_id", userId)
      .eq("account_type", "demo")
      .maybeSingle();

    if (error || !account) {
      return reply.code(FX_ERRORS.NOT_FOUND).send({
        success: false,
        error: "No demo account to reset.",
        code: "NOT_FOUND",
      });
    }

    // Close open demo positions first so reset cannot leave orphaned exposure.
    const { data: open } = await supabase
      .from("forex_positions")
      .select("id")
      .eq("account_id", account.id)
      .is("closed_at", null);

    for (const p of open ?? []) {
      await supabase
        .from("forex_positions")
        .update({ closed_at: new Date().toISOString(), close_reason: "reset", updated_at: new Date().toISOString() })
        .eq("id", p.id);
    }

    const { error: resetError } = await supabase
      .from("forex_accounts")
      .update({
        balance: DEMO_START_BALANCE,
        equity: DEMO_START_BALANCE,
        used_margin: 0,
        updated_at: new Date().toISOString(),
      })
      .eq("id", account.id);

    if (resetError) {
      logger.error({ userId, err: resetError.message }, "Demo reset failed");
      return reply.code(FX_ERRORS.INTERNAL).send({
        success: false,
        error: "Could not reset the demo account.",
        code: "INTERNAL",
      });
    }

    logger.info({ userId, closedPositions: open?.length ?? 0 }, "Forex demo account reset");
    return { success: true, balance: DEMO_START_BALANCE };
  });

  /**
   * Trade history for one mode.
   *
   * Scoped to the requested account type on the server, so demo history can
   * never leak into a real account view and vice versa. The mode comes from the
   * authenticated request, not from anything the client asserts about a record.
   */
  fastify.get("/history", { preHandler: [verifyAuth] }, async (request, reply) => {
    const { mode, limit } = request.query as { mode?: string; limit?: string };
    const accountType = mode === "live" ? "live" : "demo";
    const userId = request.user!.id;

    const n = Math.min(Math.max(Number(limit) || 100, 1), 500);

    // Orders that never became a position (pending, cancelled, rejected) still
    // belong in history, so the two sources are merged rather than the client
    // being shown only closed trades.
    const [{ data: positions, error: posErr }, { data: orders, error: ordErr }] = await Promise.all([
      supabase
        .from("forex_positions")
        .select("id,instrument_id,side,quantity,average_entry_price,closed_at,opened_at,realized_pnl,close_reason,status")
        .eq("user_id", userId)
        .not("closed_at", "is", null)
        .order("closed_at", { ascending: false })
        .limit(n),
      supabase
        .from("forex_orders")
        .select("id,instrument_id,side,quantity,order_type,status,reject_reason,created_at")
        .eq("user_id", userId)
        .in("status", ["pending", "cancelled", "rejected", "expired"])
        .order("created_at", { ascending: false })
        .limit(n),
    ]);

    if (posErr || ordErr) {
      // A PostgREST error here almost always means the database is missing a
      // column the query selects, i.e. a migration was not applied. Log the
      // database's own message so the cause is identifiable from the logs
      // instead of a bare 500.
      logger.error(
        { userId, mode: accountType, posErr: posErr?.message, ordErr: ordErr?.message },
        "Forex history query failed",
      );
      return reply.code(FX_ERRORS.INTERNAL).send({
        success: false,
        error: "Trade history is temporarily unavailable.",
        code: "INTERNAL",
      });
    }

    const enriched: Record<string, unknown>[] = [];
    for (const p of positions ?? []) {
      const symbol = await symbolForInstrument(p.instrument_id);
      enriched.push({
        id: p.id,
        kind: "position",
        mode: accountType,
        symbol,
        side: p.side,
        quantity: Number(p.quantity),
        entry: Number(p.average_entry_price),
        exit: null,
        pnl: Number(p.realized_pnl ?? 0),
        status: "closed",
        closeReason: p.close_reason ?? "manual",
        openedAt: p.opened_at,
        closedAt: p.closed_at,
      });
    }
    for (const o of orders ?? []) {
      const symbol = await symbolForInstrument(o.instrument_id);
      enriched.push({
        id: o.id,
        kind: "order",
        mode: accountType,
        symbol,
        side: o.side,
        quantity: Number(o.quantity),
        orderType: o.order_type,
        entry: null,
        exit: null,
        pnl: 0,
        status: o.status,
        reason: o.reject_reason,
        openedAt: o.created_at,
        closedAt: o.created_at,
      });
    }

    enriched.sort(
      (a, b) => new Date(String(b.closedAt)).getTime() - new Date(String(a.closedAt)).getTime(),
    );

    return {
      success: true,
      mode: accountType,
      history: enriched.slice(0, n),
    };
  });

  /** Engine health for diagnostics; never exposes credentials. */
  fastify.get("/health", async () => ({
    success: true,
    market: getEngine().describe(),
    realTradingEnabled: REAL_TRADING_ENABLED,
    symbols: SYMBOLS.length,
  }));

  /**
   * Schema and function diagnostics.
   *
   * The Forex RPCs and the sizing columns ship in SQL migrations that must be
   * applied out of band, so a partially-migrated database produced 400s and 500s
   * that were impossible to explain from the client. This reports what is
   * actually present so the failure can be identified without guessing. Read-only,
   * service-role, and it never returns credentials or user data.
   */
  fastify.get("/diagnostics", { preHandler: [verifyAuth] }, async (request, reply) => {
    const userId = request.user!.id;
    const required = [
      "forex_accounts",
      "forex_instruments",
      "forex_orders",
      "forex_positions",
      "forex_fills",
      "forex_transactions",
      "forex_market_config",
      "forex_symbol_state",
    ];
    const requiredFns = [
      "forex_open_market_position",
      "forex_close_position",
      "forex_recalculate_equity",
      "forex_account_upnl",
    ];

    const problems: string[] = [];
    const { data: tables, error: tableErr } = await supabase
      .from("information_schema.tables")
      .select("table_name")
      .eq("table_schema", "public")
      .in("table_name", required);
    if (tableErr) {
      return reply.code(500).send({ success: false, error: tableErr.message, code: "DIAGNOSTICS_FAILED" });
    }
    const present = new Set((tables ?? []).map((t: { table_name: string }) => t.table_name));
    const missingTables = required.filter((t) => !present.has(t));
    if (missingTables.length) problems.push(`Missing tables: ${missingTables.join(", ")}`);

    const { data: routines } = await supabase
      .from("information_schema.routines")
      .select("routine_name")
      .eq("routine_schema", "public")
      .in("routine_name", requiredFns);
    const presentFns = new Set((routines ?? []).map((r: { routine_name: string }) => r.routine_name));
    const missingFns = requiredFns.filter((f) => !presentFns.has(f));
    if (missingFns.length) {
      problems.push(
        `Missing database functions: ${missingFns.join(", ")}. Apply the Forex migrations in supabase/migrations.`,
      );
    }

    // Report the account the caller can actually see, which is the one whose
    // creation and equity paths the 500s came from.
    const { data: accounts, error: acctErr } = await supabase
      .from("forex_accounts")
      .select("id, account_type, balance, equity, used_margin, leverage, status")
      .eq("user_id", userId);
    if (acctErr) problems.push(`forex_accounts unreadable: ${acctErr.message}`);

    return reply.code(200).send({
      success: true,
      requiredFunctions: requiredFns,
      missingTables,
      problems,
      accounts: accounts ?? [],
      leverageDefault: configuredLeverage(),
      minTradeAmount: minTradeAmount(),
      realTradingEnabled: REAL_TRADING_ENABLED,
    });
  });
};

async function closePosition(  request: FastifyRequest,
  reply: FastifyReply,
  positionId: string,
  fraction: number,
) {
  const userId = request.user!.id;
  const { data: position } = await supabase
    .from("forex_positions")
    .select("*")
    .eq("id", positionId)
    .eq("user_id", userId)
    .maybeSingle();
  if (!position) {
    return reply.code(404).send({ success: false, error: "Position not found" });
  }
  if (position.closed_at) {
    return reply.code(409).send({ success: false, error: "Position is already closed" });
  }

  const sym = await symbolForInstrument(position.instrument_id);
  const spec = sym ? getInstrument(sym) : undefined;
  if (!spec) return reply.code(400).send({ success: false, error: "Unknown instrument" });

  const remaining = Number(position.quantity);
  const closeLots = Number((remaining * fraction).toFixed(2));
  if (closeLots <= 0) return bad(reply, "Close amount must be greater than zero");
  if (closeLots > remaining) return bad(reply, "Cannot close more than the open position");

  let exitPrice: number;
  let q2k: number;
  try {
    const quote = getEngine().quote(spec.symbol);
    // Closing a long means selling into the bid; closing a short means buying
    // back at the ask. Using the bid for both systematically under-paid a
    // short position.
    exitPrice = position.side === "buy" ? quote.bid : quote.ask;
    q2k = quoteToKes(spec);
  } catch {
    return reply.code(503).send({
      success: false,
      error: "Market data is currently unavailable. The position was not closed.",
      code: "MARKET_DATA_UNAVAILABLE",
    });
  }

  // The transaction, ledger entry, position close and margin release all happen
  // inside one database transaction, and the realised P/L is computed there from
  // the stored entry price — never accepted from this process.
  const { data: result, error: closeError } = await supabase.rpc("forex_close_position", {
    p_user_id: userId,
    p_position_id: positionId,
    p_close_lots: closeLots,
    p_exit_price: exitPrice,
    p_quote_to_kes: q2k,
  });

  if (closeError) {
    const reason = closeError.message ?? "";
    if (reason.includes("POSITION_NOT_FOUND")) {
      return reply.code(404).send({ success: false, error: "Position not found" });
    }
    if (reason.includes("POSITION_ALREADY_CLOSED")) {
      return reply.code(409).send({ success: false, error: "Position is already closed" });
    }
    if (reason.includes("OVER_CLOSE")) {
      return bad(reply, "Cannot close more than the open position");
    }
    logger.error({ err: reason }, "Forex close failed");
    return reply.code(500).send({
      success: false,
      error: "The position could not be closed. No balance was changed.",
      code: "EXECUTION_FAILED",
    });
  }

  const { data: updated } = await supabase
    .from("forex_positions")
    .select("*")
    .eq("id", positionId)
    .maybeSingle();

  return {
    success: true,
    position: updated,
    realizedPnl: Number(result?.realized_pnl ?? 0),
    exitPrice,
    balance: Number(result?.balance ?? 0),
    partial: !result?.closed,
  };
}
