/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TradingRouteImport } from './routes/trading'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as KaziRouteImport } from './routes/kazi'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as BankingRouteImport } from './routes/banking'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTradingRouteImport } from './routes/admin.trading'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminKaziRouteImport } from './routes/admin.kazi'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminCommissionsRouteImport } from './routes/admin.commissions'
import { Route as AdminBusinessRouteImport } from './routes/admin.business'
import { Route as AdminBankingRouteImport } from './routes/admin.banking'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TradingRoute = TradingRouteImport.update({
  id: '/trading',
  path: '/trading',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const KaziRoute = KaziRouteImport.update({
  id: '/kazi',
  path: '/kazi',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const BankingRoute = BankingRouteImport.update({
  id: '/banking',
  path: '/banking',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTradingRoute = AdminTradingRouteImport.update({
  id: '/trading',
  path: '/trading',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKaziRoute = AdminKaziRouteImport.update({
  id: '/kazi',
  path: '/kazi',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommissionsRoute = AdminCommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBusinessRoute = AdminBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBankingRoute = AdminBankingRouteImport.update({
  id: '/banking',
  path: '/banking',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/banking': typeof BankingRoute
  '/business': typeof BusinessRoute
  '/kazi': typeof KaziRoute
  '/profile': typeof ProfileRoute
  '/trading': typeof TradingRoute
  '/wallet': typeof WalletRoute
  '/admin/banking': typeof AdminBankingRoute
  '/admin/business': typeof AdminBusinessRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/kazi': typeof AdminKaziRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/trading': typeof AdminTradingRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/banking': typeof BankingRoute
  '/business': typeof BusinessRoute
  '/kazi': typeof KaziRoute
  '/profile': typeof ProfileRoute
  '/trading': typeof TradingRoute
  '/wallet': typeof WalletRoute
  '/admin/banking': typeof AdminBankingRoute
  '/admin/business': typeof AdminBusinessRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/kazi': typeof AdminKaziRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/trading': typeof AdminTradingRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/banking': typeof BankingRoute
  '/business': typeof BusinessRoute
  '/kazi': typeof KaziRoute
  '/profile': typeof ProfileRoute
  '/trading': typeof TradingRoute
  '/wallet': typeof WalletRoute
  '/admin/banking': typeof AdminBankingRoute
  '/admin/business': typeof AdminBusinessRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/kazi': typeof AdminKaziRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/trading': typeof AdminTradingRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/banking'
    | '/business'
    | '/kazi'
    | '/profile'
    | '/trading'
    | '/wallet'
    | '/admin/banking'
    | '/admin/business'
    | '/admin/commissions'
    | '/admin/finance'
    | '/admin/kazi'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/support'
    | '/admin/trading'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/banking'
    | '/business'
    | '/kazi'
    | '/profile'
    | '/trading'
    | '/wallet'
    | '/admin/banking'
    | '/admin/business'
    | '/admin/commissions'
    | '/admin/finance'
    | '/admin/kazi'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/support'
    | '/admin/trading'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/banking'
    | '/business'
    | '/kazi'
    | '/profile'
    | '/trading'
    | '/wallet'
    | '/admin/banking'
    | '/admin/business'
    | '/admin/commissions'
    | '/admin/finance'
    | '/admin/kazi'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/support'
    | '/admin/trading'
    | '/admin/users'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BankingRoute: typeof BankingRoute
  BusinessRoute: typeof BusinessRoute
  KaziRoute: typeof KaziRoute
  ProfileRoute: typeof ProfileRoute
  TradingRoute: typeof TradingRoute
  WalletRoute: typeof WalletRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trading': {
      id: '/trading'
      path: '/trading'
      fullPath: '/trading'
      preLoaderRoute: typeof TradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kazi': {
      id: '/kazi'
      path: '/kazi'
      fullPath: '/kazi'
      preLoaderRoute: typeof KaziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banking': {
      id: '/banking'
      path: '/banking'
      fullPath: '/banking'
      preLoaderRoute: typeof BankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/trading': {
      id: '/admin/trading'
      path: '/trading'
      fullPath: '/admin/trading'
      preLoaderRoute: typeof AdminTradingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kazi': {
      id: '/admin/kazi'
      path: '/kazi'
      fullPath: '/admin/kazi'
      preLoaderRoute: typeof AdminKaziRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commissions': {
      id: '/admin/commissions'
      path: '/commissions'
      fullPath: '/admin/commissions'
      preLoaderRoute: typeof AdminCommissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/business': {
      id: '/admin/business'
      path: '/business'
      fullPath: '/admin/business'
      preLoaderRoute: typeof AdminBusinessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banking': {
      id: '/admin/banking'
      path: '/banking'
      fullPath: '/admin/banking'
      preLoaderRoute: typeof AdminBankingRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBankingRoute: typeof AdminBankingRoute
  AdminBusinessRoute: typeof AdminBusinessRoute
  AdminCommissionsRoute: typeof AdminCommissionsRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminKaziRoute: typeof AdminKaziRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTradingRoute: typeof AdminTradingRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBankingRoute: AdminBankingRoute,
  AdminBusinessRoute: AdminBusinessRoute,
  AdminCommissionsRoute: AdminCommissionsRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminKaziRoute: AdminKaziRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTradingRoute: AdminTradingRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BankingRoute: BankingRoute,
  BusinessRoute: BusinessRoute,
  KaziRoute: KaziRoute,
  ProfileRoute: ProfileRoute,
  TradingRoute: TradingRoute,
  WalletRoute: WalletRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
